sms:
  provider: ${SMS_PROVIDER:FARAZ_SMS}
  baseUrl: ${SMS_BASE_URL:https://edge.ippanel.com/v1/api}
  fromNumber: ${SMS_FROM_NUMBER:+983000505'}
  token: ${SMS_TOKEN:YTBkN2I5ZTEtNTNhMC00MDgzLTg5OTAtNWI5YzMzYjQ4ODkxMzBhMjE0MmE0ODllYTI3MDEwNzVmNmFhZWRhZDA4M2Y=}